name: Build Docker image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: jamesgurung
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: jamesgurung/school-helpdesk:latest
          build-args: GITHUB_RUN_NUMBER=${{ github.run_number }}